steps:
  - label: "Set environment"
    command: ".buildkite/set_env.sh"

  - block: "Build Specifications"
    prompt: "Fill out build details"
    fields:
      - select: "Which context?"
        hint: "Context determines the compartment" 
        key: context
        options:
          - label: "Infra"
            value: "python-infra"
      - text: "Which directory?"
        hint: "name of the directory containing the function spec"
        key: "directory"

  - label: "Fn build and push"
    command: ".buildkite/fn_deploy.sh"