steps:
  - label: "Set environment"
    command: ".buildkite/set_env.sh"
  - input: "Build Specifications"
      fields:
        - text: "Which context?"
          hint: "Options: python-infra"
          key: context
        - text: "Which directory?"
          hint: "name of the directory containing the function spec"
          key: "directory"

    - label: "Fn build and push"
      command: ".buildkite/fn_deploy.sh"

